name: "build-and-push-to-pages"
run-name: "Build static HTML and copy to gh-pages branch"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
    types:
      - closed

jobs:
  build-and-push-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: pip install -r ./build-requirements.txt
      - run: "sh build.sh"
  





